Testnet address support (WIP)
Emurgo/react-native-cardano pull request #9
Opened 2019-08-21 14:02 UTC by rooooooooob

A simple extension of the API of `generateAddresses` to take in a
protocol magic, allowing testnet address generation.

This was done by simply extending `wallet-wasm` in `js-cardano-wasm` as
it was the simplest solution for now.

As it previously took in JSON for all params the API did not have to
change inside of `android.rs`, `ios.rs`, `rust_native_cardano.h` (or
anything in the `rust/` directory). Same for `android/.../Native.kt`.

**NOTE**: this dependency points to my own fork of `js-cardano-wasm` - once this gets merged, this PR will need to get updated to point to the official IOHK `js-cardano-wasm` dependency.

2019-08-21 14:03 UTC, rooooooooob commented
This changes the API for `generateAddresses()` by adding an extra parameter. Do we need to update the version number to reflect this? Should we avoid the API change entirely and add an extra parameter or look into having it as optional?

2019-08-23 11:54 UTC, rooooooooob commented
The `js-cardano-wasm` PR was merged into IOHK's repo. The dependency has been updated and finalized here.

2019-08-28 23:52 UTC, nicarq approved these changes

2019-08-28 23:53 UTC, nicarq requested changes
yeah, we should update `package.json` and bump up the version to `0.1.0` or something like that

2019-08-29 18:45 UTC, merged